       PROGRAM PARALLEL DEFAULT
	IMPLICIT NONE
	INTEGER :: I,J,ISUCCESS
         
       J=0
       ISUCCESS=1 
!$OMP PARALLEL NUM_THREADS(4) DEFAULT(NONE) SHARED(ISUCCESS,I,J)
!$OMP DO REDUCTION(+:J)
 	  DO I=1,1600
	     J=J+I
  	  END DO
!$OMP END DO
! CHECK THAT ALL THREADS HAVE THE CORRECT VALUE AFTER DO LOOP
        IF (J/=(1+1600)*1600/2) THEN
   	   ISUCCESS=0 
        ENDIF
!$OMP END PARALLEL
       IF (ISUCCESS .EQ. 1) THEN
          WRITE(*,*) ' TEST : PARALLEL DEFAULT and REDUCTION PASSED'
       ELSE
          WRITE(*,*) ' TEST : PARALLEL DEFAULT and REDUCTION FAILED'
       ENDIF   
       END PROGRAM PARALLEL DEFAULT