       PROGRAM PARALLEL NUM_THREADS
	IMPLICIT NONE
	INTEGER :: I,J
       J=0
!$OMP PARALLEL NUM_THREADS(4) SHARED(I)
       I = OMP_GET_NUM_THREADS()    
!$OMP END PARALLEL
       IF (I .EQ. 4 ) THEN
          WRITE(*,*) ' TEST : PARALLEL NUM_THREADS PASSED'
       ELSE
          WRITE(*,*) ' TEST : PARALLEL NUM_THREADS FAILED'
       ENDIF
       END PROGRAM 
