       PROGRAM PARALLEL IF
	INTEGER :: FLAG 
        
       FLAG = 0
!$OMP PARALLEL IF (OMP_GET_NUM_PROCS() .NE. 0) 
!$OMP PARALLEL SHARED(SUM)
          FLAG = 1
!$OMP END PARALLEL
!$OMP END PARALLEL
       WRITE (1,*) "TEST PRARALLEL IF PASSED"
       IF (FLAG .EQ. 1) THEN
           WRITE (*,*) "TEST PARALLEL IF PASSED"
       ELSE
           WRITE (*,*) "TEST PARALLEL IF FAILED"
       END IF
       END PROGRAM PARALLEL IF
