       PROGRAM TO TEST OMP_GET_WTICK
       INCLUDE "omp_lib.h" ! or USE OMP_LIB
       REAL STARTT,ENDT;
       INTEGER NTHREADS;

       CALL OMP_SET_NUM_THREADS(4)       
!$OMP PARALLEL PRIVATE(TID)
       STARTT = OMP_GET_WTICK() 
       NTHREADS = OMP_GET_NUM_THREADS()
       ENDT = OMP_GET_WTICK() 
!$OMP END PARALLEL
!        write (*,*) 'There OMP_GET_WTICK DIFFERENCE = ', STARTT - ENDT
      END
