#!/bin/sh -u
# ====================================================================
#
# Copyright (C) 2011, Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Open64 is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# Open64 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.
#
# ====================================================================

# The underlying limit.pl script only works with particular versions
# of perl.  Unfortunately, we do not have consistent paths on our
# machines, so we implement this hideous search process (which,
# incidentally, does not seem to work if we do it in perl -- exec-ing
# a "good" perl from a "bad" perl elicits the "bad" signal behavior).

PERL_SCRIPT=$(dirname $0)/limit.pl

PERL_PATHS="/usr/local/bin/perl /usr/bin/perl /opt/perl/bin/perl /app/perl"
for PERL_PATH in ${PERL_PATHS} ; do
  if [[ -r ${PERL_PATH} ]] && ${PERL_PATH} ${PERL_SCRIPT} -version
  then
    exec ${PERL_PATH} ${PERL_SCRIPT} "${@:-}"
  fi
done
echo >&2 "$(basename $0): No suitable version of perl available"
exit 143
